/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class', // Enable dark mode based on the 'dark' class on the HTML element
  safelist: [
    // Theme background gradients - light mode
    'bg-gradient-to-br',
    'from-gray-50',
    'to-white',
    'from-stone-50',
    'to-amber-50',
    'from-slate-50',
    'to-gray-50',
    'from-sky-50',
    'to-blue-50',
    // Theme background gradients - dark mode
    'from-gray-900',
    'to-black',
    'from-stone-900',
    'to-amber-900',
    'from-slate-900',
    'to-gray-900',
    'from-sky-900',
    'to-blue-900',
    'from-gray-800',
    'to-gray-900',
    // Theme UI gradients - light mode
    'bg-gradient-to-r',
    'from-gray-600',
    'to-gray-700',
    'from-amber-500',
    'to-orange-600',
    'from-slate-500',
    'to-slate-600',
    'from-sky-500',
    'to-blue-600',
    'from-gray-500',
    'to-gray-600',
    // Theme UI gradients - dark mode
    'from-gray-300',
    'to-gray-400',
    'from-amber-400',
    'to-orange-500',
    'from-slate-400',
    'to-slate-500',
    'from-sky-400',
    'to-blue-500',
    'from-gray-400',
    'to-gray-500',
    // Sky-blue theme colors
    'bg-sky-50',
    'bg-blue-50',
    'bg-sky-900',
    'bg-blue-900',
    'bg-sky-500',
    'bg-blue-600',
    'bg-sky-400',
    'bg-blue-500',
    'bg-sky-600',
    'bg-sky-700',
    'bg-sky-300',
    'bg-sky-800',
    'text-sky-900',
    'text-blue-800',
    'text-blue-600',
    'text-sky-100',
    'text-blue-200',
    'text-blue-400',
    'border-blue-200',
    'border-blue-700',
    'bg-cyan-100',
    'bg-cyan-900',
    // Theme text colors
    'text-gray-900',
    'text-gray-700',
    'text-gray-500',
    'text-gray-100',
    'text-gray-300',
    'text-stone-900',
    'text-amber-900',
    'text-amber-700',
    'text-stone-100',
    'text-amber-200',
    'text-amber-400',
    'text-slate-900',
    'text-slate-700',
    'text-slate-500',
    'text-slate-100',
    'text-slate-300',
    'text-sky-900',
    'text-blue-800',
    'text-blue-600',
    'text-sky-100',
    'text-blue-200',
    'text-blue-400',
    // Theme card colors
    'bg-white',
    'bg-stone-50',
    'bg-slate-50',
    'bg-sky-50',
    'bg-gray-800',
    'bg-stone-800',
    'bg-slate-800',
    'bg-sky-800',
    'border-gray-200',
    'border-amber-200',
    'border-slate-200',
    'border-blue-200',
    'border-gray-700',
    'border-amber-700',
    'border-slate-700',
    'border-blue-700',
    // Theme subtle backgrounds
    'bg-gray-50',
    'bg-amber-50',
    'bg-gray-50',
    'bg-blue-50',
    'bg-gray-100',
    'bg-amber-100',
    'bg-slate-100',
    'bg-blue-100',
    'bg-gray-900',
    'bg-stone-900',
    'bg-slate-900',
    'bg-sky-900',
    'bg-gray-700',
    'bg-amber-800',
    'bg-slate-700',
    'bg-blue-800',
  ],
  theme: {
    extend: {
      fontFamily: {
        display: ['Fraunces', 'Amiri', 'Georgia', 'Times New Roman', 'serif'],
        sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
        arabic: ['Amiri', 'Fraunces', 'Georgia', 'serif'],
      },
      colors: {
        // ---- Scholar role-based tokens (spec) ----
        'page':              'var(--bg-page)',
        'sidebar':           'var(--bg-sidebar)',
        'card-dark':         'var(--bg-card-dark)',
        'card-light':        'var(--bg-card-light)',
        'accent-gold':       'var(--accent-gold)',
        'accent-gold-soft':  'var(--accent-gold-soft)',
        'ink':               'var(--text-primary-dark)',
        'ink-on-dark':       'var(--text-primary-light)',
        'muted-ink':         'var(--text-muted-dark)',
        'muted-ink-on-dark': 'var(--text-muted-light)',
        'divider':           'var(--divider)',
        'divider-on-dark':   'var(--divider-dark)',

        // ---- Legacy aliases (kept until phases 3–13 migrate consumers) ----
        'theme-bg-from':     'var(--theme-bg-from, var(--bg-page))',
        'theme-bg-to':       'var(--theme-bg-to, var(--bg-page))',
        'theme-primary-from':'var(--theme-primary-from, var(--accent-gold))',
        'theme-primary-to':  'var(--theme-primary-to, var(--accent-gold-soft))',
        'theme-accent':      'var(--theme-accent, var(--accent-gold))',
      },
    },
  },
  plugins: [],
};
